#pragma once
#include <Windows.h>


//----------------------------------------------------------------------------------------------------------------------------------------------------
// キーコード列挙型
//----------------------------------------------------------------------------------------------------------------------------------------------------
enum class KeyCode
{
    A = 'A',
    B = 'B',
    C = 'C',
    D = 'D',
    E = 'E',
    F = 'F',
    G = 'G',
    H = 'H',
    I = 'I',
    J = 'J',
    K = 'K',
    L = 'L',
    M = 'M',
    N = 'N',
    O = 'O',
    P = 'P',
    Q = 'Q',
    R = 'R',
    S = 'S',
    T = 'T',
    U = 'U',
    V = 'V',
    W = 'W',
    X = 'X',
    Y = 'Y',
    Z = 'Z',
    Alpha0 = 0x30,
    Alpha1 = 0x31,
    Alpha2 = 0x32,
    Alpha3 = 0x33,
    Alpha4 = 0x34,
    Alpha5 = 0x35,
    Alpha6 = 0x36,
    Alpha7 = 0x37,
    Alpha8 = 0x38,
    Alpha9 = 0x39,
    Keypad0 = VK_NUMPAD0,
    Keypad1 = VK_NUMPAD1,
    Keypad2 = VK_NUMPAD2,
    Keypad3 = VK_NUMPAD3,
    Keypad4 = VK_NUMPAD4,
    Keypad5 = VK_NUMPAD5,
    Keypad6 = VK_NUMPAD6,
    Keypad7 = VK_NUMPAD7,
    Keypad8 = VK_NUMPAD8,
    Keypad9 = VK_NUMPAD9,
    Space = VK_SPACE,
    Enter = VK_RETURN,
    LeftShift = VK_LSHIFT,
    RightShift = VK_RSHIFT,
    LeftControl = VK_LCONTROL,
    RightControl = VK_RCONTROL,
    Escape = VK_ESCAPE,
    F1 = VK_F1,
    F2 = VK_F2,
    F3 = VK_F3,
    F4 = VK_F4,
    F5 = VK_F5,
    F6 = VK_F6,
    F7 = VK_F7,
    F8 = VK_F8,
    F9 = VK_F9,
    F10 = VK_F10,
    F11 = VK_F11,
    F12 = VK_F12,
    F13 = VK_F13,
    F14 = VK_F14,
    F15 = VK_F15,
    UpArrow = VK_UP,
    DownArrow = VK_DOWN,
    LeftArrow = VK_LEFT,
    RightArrow = VK_RIGHT,
};