#pragma once

inline const std::map<KeyCode, std::string> KeyCodeToString = {
    {KeyCode::A, "a"},
    {KeyCode::B, "b"},
    {KeyCode::C, "c"},
    {KeyCode::D, "d"},
    {KeyCode::E, "e"},
    {KeyCode::F, "f"},
    {KeyCode::G, "g"},
    {KeyCode::H, "h"},
    {KeyCode::I, "i"},
    {KeyCode::J, "j"},
    {KeyCode::K, "k"},
    {KeyCode::L, "l"},
    {KeyCode::M, "m"},
    {KeyCode::N, "n"},
    {KeyCode::O, "o"},
    {KeyCode::P, "p"},
    {KeyCode::Q, "q"},
    {KeyCode::R, "r"},
    {KeyCode::S, "s"},
    {KeyCode::T, "t"},
    {KeyCode::U, "u"},
    {KeyCode::V, "v"},
    {KeyCode::W, "w"},
    {KeyCode::X, "x"},
    {KeyCode::Y, "y"},
    {KeyCode::Z, "z"},

    {KeyCode::Alpha0, "0"},
    {KeyCode::Alpha1, "1"},
    {KeyCode::Alpha2, "2"},
    {KeyCode::Alpha3, "3"},
    {KeyCode::Alpha4, "4"},
    {KeyCode::Alpha5, "5"},
    {KeyCode::Alpha6, "6"},
    {KeyCode::Alpha7, "7"},
    {KeyCode::Alpha8, "8"},
    {KeyCode::Alpha9, "9"},

    {KeyCode::Keypad0, "keypad0"},
    {KeyCode::Keypad1, "keypad1"},
    {KeyCode::Keypad2, "keypad2"},
    {KeyCode::Keypad3, "keypad3"},
    {KeyCode::Keypad4, "keypad4"},
    {KeyCode::Keypad5, "keypad5"},
    {KeyCode::Keypad6, "keypad6"},
    {KeyCode::Keypad7, "keypad7"},
    {KeyCode::Keypad8, "keypad8"},
    {KeyCode::Keypad9, "keypad9"},

    {KeyCode::Space, "space"},
    {KeyCode::Enter, "enter"},
    {KeyCode::LeftShift, "shift"},
    {KeyCode::RightShift, "shift"},
    {KeyCode::LeftControl, "control"},
    {KeyCode::RightControl, "control"},
    {KeyCode::Escape, "escape"},

    {KeyCode::F1, "f1"},
    {KeyCode::F2, "f2"},
    {KeyCode::F3, "f3"},
    {KeyCode::F4, "f4"},
    {KeyCode::F5, "f5"},
    {KeyCode::F6, "f6"},
    {KeyCode::F7, "f7"},
    {KeyCode::F8, "f8"},
    {KeyCode::F9, "f9"},
    {KeyCode::F10, "f10"},
    {KeyCode::F11, "f11"},
    {KeyCode::F12, "f12"},
    {KeyCode::F13, "f13"},
    {KeyCode::F14, "f14"},
    {KeyCode::F15, "f15"},

    {KeyCode::UpArrow, "uparrow"},
    {KeyCode::DownArrow, "downarrow"},
    {KeyCode::LeftArrow, "leftarrow"},
    {KeyCode::RightArrow, "rightarrow"},

    {KeyCode::Mouse0, "mouse_left"},
    {KeyCode::Mouse1, "mouse_right"},
    {KeyCode::Mouse2, "mouse_middle"},
    {KeyCode::Mouse3, "mouse_x1"},
    {KeyCode::Mouse4, "mouse_x2"},
};

inline const std::map<std::string, KeyCode> StringToKeyCode =
{
	{ "a", KeyCode::A },
	{ "b", KeyCode::B },
	{ "c", KeyCode::C },
	{ "d", KeyCode::D },
	{ "e", KeyCode::E },
	{ "f", KeyCode::F },
	{ "g", KeyCode::G },
	{ "h", KeyCode::H },
	{ "i", KeyCode::I },
	{ "j", KeyCode::J },
	{ "k", KeyCode::K },
	{ "l", KeyCode::L },
	{ "m", KeyCode::M },
	{ "n", KeyCode::N },
	{ "o", KeyCode::O },
	{ "p", KeyCode::P },
	{ "q", KeyCode::Q },
	{ "r", KeyCode::R },
	{ "s", KeyCode::S },
	{ "t", KeyCode::T },
	{ "u", KeyCode::U },
	{ "v", KeyCode::V },
	{ "w", KeyCode::W },
	{ "x", KeyCode::X },
	{ "y", KeyCode::Y },
	{ "z", KeyCode::Z },

	{ "0", KeyCode::Alpha0 },
	{ "1", KeyCode::Alpha1 },
	{ "2", KeyCode::Alpha2 },
	{ "3", KeyCode::Alpha3 },
	{ "4", KeyCode::Alpha4 },
	{ "5", KeyCode::Alpha5 },
	{ "6", KeyCode::Alpha6 },
	{ "7", KeyCode::Alpha7 },
	{ "8", KeyCode::Alpha8 },
	{ "9", KeyCode::Alpha9 },

	{ "keypad0", KeyCode::Keypad0 },
	{ "keypad1", KeyCode::Keypad1 },
	{ "keypad2", KeyCode::Keypad2 },
	{ "keypad3", KeyCode::Keypad3 },
	{ "keypad4", KeyCode::Keypad4 },
	{ "keypad5", KeyCode::Keypad5 },
	{ "keypad6", KeyCode::Keypad6 },
	{ "keypad7", KeyCode::Keypad7 },
	{ "keypad8", KeyCode::Keypad8 },
	{ "keypad9", KeyCode::Keypad9 },

	{ "space", KeyCode::Space },
	{ "enter", KeyCode::Enter },
	{ "left_shift", KeyCode::LeftShift },
	{ "right_shift", KeyCode::RightShift },
	{ "control", KeyCode::LeftControl },
	{ "escape", KeyCode::Escape },

	{ "f1", KeyCode::F1 },
	{ "f2", KeyCode::F2 },
	{ "f3", KeyCode::F3 },
	{ "f4", KeyCode::F4 },
	{ "f5", KeyCode::F5 },
	{ "f6", KeyCode::F6 },
	{ "f7", KeyCode::F7 },
	{ "f8", KeyCode::F8 },
	{ "f9", KeyCode::F9 },
	{ "f10", KeyCode::F10 },
	{ "f11", KeyCode::F11 },
	{ "f12", KeyCode::F12 },
	{ "f13", KeyCode::F13 },
	{ "f14", KeyCode::F14 },
	{ "f15", KeyCode::F15 },

	{ "uparrow", KeyCode::UpArrow },
	{ "downarrow", KeyCode::DownArrow },
	{ "leftarrow", KeyCode::LeftArrow },
	{ "rightarrow", KeyCode::RightArrow },

	{ "mouse_left", KeyCode::Mouse0 },
	{ "mouse_right", KeyCode::Mouse1 },
	{ "mouse_middle", KeyCode::Mouse2 },
	{ "mouse_x1", KeyCode::Mouse3 },
	{ "mouse_x2", KeyCode::Mouse4 },
};

inline const std::map<GamepadButton, std::string> GamepadButtonToString =
{
    { GamepadButton::South,            "gamepad_south" },
    { GamepadButton::East,             "gamepad_east" },
    { GamepadButton::West,             "gamepad_west" },
    { GamepadButton::North,            "gamepad_north" },

    { GamepadButton::DpadDown,         "gamepad_dpad_down" },
    { GamepadButton::DpadRight,        "gamepad_dpad_right" },
    { GamepadButton::DpadLeft,         "gamepad_dpad_left" },
    { GamepadButton::DpadUp,           "gamepad_dpad_up" },

    { GamepadButton::LeftShoulder,     "gamepad_left_shoulder" },
    { GamepadButton::LeftTrigger,      "gamepad_left_trigger" },
    { GamepadButton::LeftStickButton,  "gamepad_left_stick" },

    { GamepadButton::RightShoulder,    "gamepad_right_shoulder" },
    { GamepadButton::RightTrigger,     "gamepad_right_trigger" },
    { GamepadButton::RightStickButton, "gamepad_right_stick" },

    { GamepadButton::Select,           "gamepad_select" },
    { GamepadButton::Start,            "gamepad_start" },
};

inline const std::map<std::string, GamepadButton> StringToGamepadButton =
{
	{ "gamepad_south",            GamepadButton::South },
	{ "gamepad_east",             GamepadButton::East },
	{ "gamepad_west",             GamepadButton::West },
	{ "gamepad_north",             GamepadButton::North },

	{ "gamepad_dpad_down",        GamepadButton::DpadDown },
	{ "gamepad_dpad_right",       GamepadButton::DpadRight },
	{ "gamepad_dpad_left",        GamepadButton::DpadLeft },
	{ "gamepad_dpad_up",          GamepadButton::DpadUp },

	{ "gamepad_left_shoulder",    GamepadButton::LeftShoulder },
	{ "gamepad_left_trigger",     GamepadButton::LeftTrigger },
	{ "gamepad_left_stick",       GamepadButton::LeftStickButton },

	{ "gamepad_right_shoulder",   GamepadButton::RightShoulder },
	{ "gamepad_right_trigger",    GamepadButton::RightTrigger },
	{ "gamepad_right_stick",      GamepadButton::RightStickButton },

	{ "gamepad_select",           GamepadButton::Select },
	{ "gamepad_start",            GamepadButton::Start },
};