#pragma once

inline const std::map<KeyCode, std::string> KeyCodeToString = {
    {KeyCode::A, "a"},
    {KeyCode::B, "b"},
    {KeyCode::C, "c"},
    {KeyCode::D, "d"},
    {KeyCode::E, "e"},
    {KeyCode::F, "f"},
    {KeyCode::G, "g"},
    {KeyCode::H, "h"},
    {KeyCode::I, "i"},
    {KeyCode::J, "j"},
    {KeyCode::K, "k"},
    {KeyCode::L, "l"},
    {KeyCode::M, "m"},
    {KeyCode::N, "n"},
    {KeyCode::O, "o"},
    {KeyCode::P, "p"},
    {KeyCode::Q, "q"},
    {KeyCode::R, "r"},
    {KeyCode::S, "s"},
    {KeyCode::T, "t"},
    {KeyCode::U, "u"},
    {KeyCode::V, "v"},
    {KeyCode::W, "w"},
    {KeyCode::X, "x"},
    {KeyCode::Y, "y"},
    {KeyCode::Z, "z"},

    {KeyCode::Alpha0, "0"},
    {KeyCode::Alpha1, "1"},
    {KeyCode::Alpha2, "2"},
    {KeyCode::Alpha3, "3"},
    {KeyCode::Alpha4, "4"},
    {KeyCode::Alpha5, "5"},
    {KeyCode::Alpha6, "6"},
    {KeyCode::Alpha7, "7"},
    {KeyCode::Alpha8, "8"},
    {KeyCode::Alpha9, "9"},

    {KeyCode::Keypad0, "keypad0"},
    {KeyCode::Keypad1, "keypad1"},
    {KeyCode::Keypad2, "keypad2"},
    {KeyCode::Keypad3, "keypad3"},
    {KeyCode::Keypad4, "keypad4"},
    {KeyCode::Keypad5, "keypad5"},
    {KeyCode::Keypad6, "keypad6"},
    {KeyCode::Keypad7, "keypad7"},
    {KeyCode::Keypad8, "keypad8"},
    {KeyCode::Keypad9, "keypad9"},

    {KeyCode::Space, "space"},
    {KeyCode::Enter, "enter"},
    {KeyCode::LeftShift, "shift"},
    {KeyCode::RightShift, "shift"},
    {KeyCode::LeftControl, "control"},
    {KeyCode::RightControl, "control"},
    {KeyCode::Escape, "escape"},

    {KeyCode::F1, "f1"},
    {KeyCode::F2, "f2"},
    {KeyCode::F3, "f3"},
    {KeyCode::F4, "f4"},
    {KeyCode::F5, "f5"},
    {KeyCode::F6, "f6"},
    {KeyCode::F7, "f7"},
    {KeyCode::F8, "f8"},
    {KeyCode::F9, "f9"},
    {KeyCode::F10, "f10"},
    {KeyCode::F11, "f11"},
    {KeyCode::F12, "f12"},
    {KeyCode::F13, "f13"},
    {KeyCode::F14, "f14"},
    {KeyCode::F15, "f15"},

    {KeyCode::UpArrow, "uparrow"},
    {KeyCode::DownArrow, "downarrow"},
    {KeyCode::LeftArrow, "leftarrow"},
    {KeyCode::RightArrow, "rightarrow"},

    {KeyCode::Mouse0, "mouse_left"},
    {KeyCode::Mouse1, "mouse_right"},
    {KeyCode::Mouse2, "mouse_middle"},
    {KeyCode::Mouse3, "mouse_x1"},
    {KeyCode::Mouse4, "mouse_x2"},
};

inline const std::map<GamepadButton, std::string> GamepadButtonToString =
{
    { GamepadButton::South,            "gamepad_south" },
    { GamepadButton::East,             "gamepad_east" },
    { GamepadButton::West,             "gamepad_west" },
    { GamepadButton::North,            "gamepad_north" },

    { GamepadButton::DpadDown,         "gamepad_dpad_down" },
    { GamepadButton::DpadRight,        "gamepad_dpad_right" },
    { GamepadButton::DpadLeft,         "gamepad_dpad_left" },
    { GamepadButton::DpadUp,           "gamepad_dpad_up" },

    { GamepadButton::LeftShoulder,     "gamepad_left_shoulder" },
    { GamepadButton::LeftTrigger,      "gamepad_left_trigger" },
    { GamepadButton::LeftStickButton,  "gamepad_left_stick" },

    { GamepadButton::RightShoulder,    "gamepad_right_shoulder" },
    { GamepadButton::RightTrigger,     "gamepad_right_trigger" },
    { GamepadButton::RightStickButton, "gamepad_right_stick" },

    { GamepadButton::Select,           "gamepad_select" },
    { GamepadButton::Start,            "gamepad_start" },
};